version: '3'
services:
  app:
      build: .
      environment:
        PORT: 5900
        DATABASE_URL: "postgres://user:password@db:5432"
        PRIVATE_KEY: "8w7398iuvh98wf8y61$%^%nwe8fu09wufwejf"
      ports:
        - "5000:5000"
      depends_on:
        - db
  db:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    command:
      - "postgres"
      - "-c"
      - "wal_level=logical"  
  